= 토이옥션 API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

= 개요

본 문서는 토이옥션 API Document 입니다.

== HTTP 동사

본 REST API 에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP 와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 덮어쓸 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===


== HTTP 상태 코드

본 REST API 에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP 와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `401 Unauthorized`
| 인증되지 않은 경우.

| `403 Forbidden`
| 인증은 되었지만 권한이 없는 경우.

| `404 Not Found`
| 요청한 리소스가 없음.

| `500 Internal Server Error`
| 서버 오류.

| `502 Bad Gateway`
| 과도한 트래픽으로 서버장애가 발생하여 실제 서비스 IP 를 찾지 못한 경우
|===

== 응답 본문

- 응답 데이터는 JSON 으로 응답 한다.
- key 네이밍 포맷은 camel case 를 사용 한다.
- value 값이 null 이거나 빈값인 경우는 최소화 한다. 필요하다면 사용 한다. value 타입이 배열인 경우 null이 아닌 [] 값을 응답 한다.
- 응답 데이터 포맷은 아래와 같은 규칙을 따른다.

=== 응답 데이터가 없는 경우

[source,json]
----
{
    "success": true
}
----

=== 단일 데이터가 없는 경우

[source,json]
----
{
    "success": true,
    "data": {
        "id":1,
        "name":"gumi"
    }
}
----

=== 데이터가 리스트 인 경우

[source,json]
----
{
    "success": true,
    "data": [
        {
            "id":1,
            "name":"gumi"
        },
        {
            "id":2,
            "name":"gumi2"
        }
    ]
}
----

=== 요청에 실패한 경우( errors 가 없는경우 )

[source,json]
----
{
    "success": false,
    "code": "USER_001",
    "message": "이미 중복된 닉네임 입니다."
}
----

=== 요청에 실패한 경우( errors 가 있는경우 )

[source,json]
----
{
    "success": false,
    "code": "COMMON_001",
    "errors": [
        {
            "field": "username",
            "reason": "username 은(는) 12자 이상 입력해야 합니다."
        },
        {
            "field": "password",
            "reason": "password 은(는) 12자 이상 입력해야 합니다."
        }
    ],
    "message": "요청값이 잘못되었습니다."
}
----

=== 오류코드

응답에 실패 할 경우 아래와 같은 오류 코드를 응답 합니다.

==== 공통 오류코드

|===
| 오류코드 | 상태응답 | 내용

|G0000
|INTERNAL_SERVER_ERROR
|정의되지 않은 오류

|G0001
|BAD_REQUEST
|잘못된 요청값 입니다.

|G0002
|NOT_FOUND
|존재하지 않습니다.

|G0003
|BAD_REQUEST
|잘못된 값

|G0004
|BAD_REQUEST
|지원하지 않는 메소드

|G0005
|BAD_REQUEST
|필수 요청 본문이 누락되었습니다.

|G0006
|BAD_REQUEST
|허용되지 않는 콘텐츠 유형을 요청했습니다.
|===

==== 파일 오류코드

|===
| 오류코드 | 상태응답 | 내용

|F0000
|INTERNAL_SERVER_ERROR
|파일 업로드에 실패 했습니다.

|F0001
|BAD_REQUEST
|업로드할 수 없는 파일 형식입니다.
|===

= 리소스 API

== 상품

=== 상품 등록

상품을 등록할 수 있다.

operation::post-product[snippets='http-request,request-fields,http-response,response-fields']

=== 상품 조회

productId 로 상품을 조회할 수 있다.

operation::get-product[snippets='path-parameters,http-request,http-response,response-fields']

=== 상품 삭제

productId 로 상품을 삭제할 수 있다.

operation::delete-product[snippets='path-parameters,http-request,http-response,response-fields']

== 파일

파일 타입

|===
| fileType | 내용

|PRODUCT_IMAGE
|상품 이미지

|===

=== 파일 등록

현재 업로드 가능한 확장자 : jpg, png

최대 업로드 가능한 용량 : 1GB

operation::post-file[snippets='http-request,http-response,response-fields']


== 알림

=== 알림 목록 조회

알림 목록을 조회할 수 있다.

operation::get-alerts[snippets='http-request,http-response,response-fields']

=== 알림 확인

알림 확인을 통해 읽음 처리를 할 수 있다.

operation::post-alert[snippets='path-parameters,http-request,http-response,response-fields']